const express = require('express');
const path = require('node:path');
const fs = require('node:fs/promises');
const { randomUUID } = require('node:crypto');

const UUID = /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/;
const DAY = /^\d{4}-\d{2}-\d{2}$/;

// Opt-in, same-origin collector. Paths are generated by the server, never by clients.
async function createClientDiagnosticsRouter({ directory, maxSessionBytes = 20 * 1024 * 1024,
  maxTotalBytes = 256 * 1024 * 1024, maxSessions = 128, now = Date.now } = {}) {
  const router = express.Router();
  router.use((req, res, next) => {
    res.set('Cache-Control', 'no-store');
    if (!directory) return res.sendStatus(404);
    if (req.get('origin') !== `${req.protocol}://${req.get('host')}`) return res.sendStatus(403);
    next();
  });
  if (!directory) return router;

  const root = path.resolve(directory);
  await fs.mkdir(root, { recursive: true, mode: 0o700 });
  let totalBytes = 0;
  for (const date of await fs.readdir(root, { withFileTypes: true })) {
    if (!date.isDirectory() || !DAY.test(date.name)) continue;
    for (const file of await fs.readdir(path.join(root, date.name), { withFileTypes: true })) {
      if (file.isFile() && UUID.test(file.name.replace(/\.jsonl$/, '')) && file.name.endsWith('.jsonl')) {
        totalBytes += (await fs.stat(path.join(root, date.name, file.name))).size;
      }
    }
  }
  const sessions = new Map();
  let writes = Promise.resolve();
  const serialize = operation => {
    const result = writes.then(operation);
    writes = result.catch(() => {});
    return result;
  };
  router.use(express.json({ limit: '48kb', strict: true, inflate: false }));

  router.post('/sessions', async (req, res, next) => {
    try {
      await serialize(async () => {
        const time = now();
        for (const [id, session] of sessions) if (time - session.created > 24 * 60 * 60 * 1000) sessions.delete(id);
        if (sessions.size >= maxSessions || totalBytes >= maxTotalBytes) return res.sendStatus(507);
        const id = randomUUID();
        const date = new Date(time).toISOString().slice(0, 10);
        const folder = path.join(root, date);
        await fs.mkdir(folder, { recursive: true, mode: 0o700 });
        const file = path.join(folder, `${id}.jsonl`);
        const header = JSON.stringify({ event: 'collector.session', receivedAt: new Date(time).toISOString(), session: id }) + '\n';
        if (totalBytes + Buffer.byteLength(header) > maxTotalBytes) return res.sendStatus(507);
        await fs.writeFile(file, header, { flag: 'wx', mode: 0o600 });
        totalBytes += Buffer.byteLength(header);
        sessions.set(id, { file, created: time, bytes: Buffer.byteLength(header), sequence: 0 });
        res.status(201).json({ session: id });
      });
    } catch (error) { next(error); }
  });

  router.post('/sessions/:id/events', async (req, res, next) => {
    const { sequence, entries } = req.body || {};
    if (!UUID.test(req.params.id) || !Number.isSafeInteger(sequence) || sequence < 1 ||
      !Array.isArray(entries) || entries.length < 1 || entries.length > 100 ||
      entries.some(entry => !entry || typeof entry !== 'object' || Array.isArray(entry) ||
        typeof entry.event !== 'string' || entry.event.length > 80 ||
        typeof entry.time !== 'string' || entry.time.length > 40 ||
        !Number.isFinite(entry.elapsedMs) || Buffer.byteLength(JSON.stringify(entry)) > 8192)) {
      return res.sendStatus(400);
    }
    try {
      await serialize(async () => {
        const session = sessions.get(req.params.id);
        if (!session || now() - session.created > 24 * 60 * 60 * 1000) return res.sendStatus(404);
        // Retried fetches and pagehide beacons may deliver the same batch twice.
        if (sequence <= session.sequence) return res.sendStatus(204);
        if (sequence !== session.sequence + 1) return res.sendStatus(409);
        const receivedAt = new Date(now()).toISOString();
        const content = entries.map(entry => JSON.stringify({ ...entry, receivedAt, batch: sequence })).join('\n') + '\n';
        const bytes = Buffer.byteLength(content);
        if (session.bytes + bytes > maxSessionBytes || totalBytes + bytes > maxTotalBytes) return res.sendStatus(507);
        await fs.appendFile(session.file, content);
        session.bytes += bytes;
        totalBytes += bytes;
        session.sequence = sequence;
        res.sendStatus(204);
      });
    } catch (error) { next(error); }
  });
  router.use((error, req, res, next) => {
    // Report failure to the client; never expose filesystem paths or request data.
    res.status(error.status || 500).json({ error: 'Diagnostics upload failed' });
  });
  return router;
}

module.exports = { createClientDiagnosticsRouter };
